apiVersion: apps/v1
kind: Deployment
metadata:
 name: clock-app
 labels:
   app: clock-clock-app
spec:
 replicas: 1
 selector:
   matchLabels:
     app: clock-app
 template:
   metadata:
     labels:
       app: clock-app
   spec:
     imagePullSecrets:
     - name: regcred
     containers:
     - name: clock-app
       image: registry4demos.azurecr.io/patriciochavez/clock-app
       ports:
       - containerPort: 3000
       - containerPort: 1883
       - containerPort: 9001
