apiVersion: v1
kind: Pod
metadata:
 name: clockbroker
 labels:
   app: clockbroker
spec:
 containers:
   - name: clockbroker
     image: jumpingvm.example.com:5000/patriciochavez/clockbroker:latest
     command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
